### ISSUE TITLE
cmd vel not shown

### ISSUE THREAD

**Issue by DesiganBR** [jerinpeter/myrobot_description#1]
Hello
Im working on a project in ros where i need to work on urdf of two wheeled robot with differential drive plugin.
But the cmd_vel is not found. what can i do to rectify it.
i have made  a simple model still it isnt working.
perviously it was working but i dont kow what happened now its not working

**Comment by jerinpeter** [comment]
This repository only provides you with the urdf. I.e the plugins are not added. Follow my YouTube tutorials to add them.
